version: '3'

services:
  frontend:
    image: frontend:latest
    build:
      context: .
      dockerfile: frontend.dockerfile
    ports:
      - "8000:8000"

  backend:
    image: backend:latest
    build:
      context: .
      dockerfile: backend.dockerfile
    ports:
      - "8001:8001"
