name: Deploy docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  test_scripts:
    strategy:
      matrix:
        scripts: [
          "s1_development_environment/exercise_files/fc_model.py",
          "s1_development_environment/exercise_files/helper.py",
        ]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_exercises.txt
      - name: Run script
        run: python ${{ matrix.scripts }}


